coverage:
  status:
    project:
      default: false
    patch:
      default: false
      python:
        paths:
        - "src/sentry"
        ignore:
        - "src/sentry/static/sentry"
        target: 90%
      javascript:
        paths:
        - "src/sentry/static/sentry/app"
        target: 75%
  ignore:
  - src/sentry/lint/.*
  - src/sentry/runner/.*
  - src/sentry/debug/.*
  - src/.*?/migrations/.*
  - src/.*?/south_migrations/.*
  - src/bitfield/.*
  - src/debug_toolbar/.*
  - src/social_auth/.*
  - src/south/.*
comment: false
